const puppeteer = require('puppeteer');
const { env } = require('../../config/env');

function escapeHtml(value) {
  return String(value || '')
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;')
    .replace(/'/g, '&#039;');
}

function renderList(items) {
  return items.map((item) => `<li>${escapeHtml(item)}</li>`).join('');
}

function buildHTMLTemplate(data) {
  return `<!DOCTYPE html>
  <html lang="en">
    <head>
      <meta charset="utf-8" />
      <title>Proplytics Proposal Export</title>
      <style>
        body { font-family: Arial, sans-serif; color: #162032; margin: 0; padding: 32px; line-height: 1.6; }
        h1, h2, h3 { margin: 0 0 12px; color: #19395c; }
        h1 { font-size: 28px; }
        h2 { font-size: 18px; margin-top: 28px; border-bottom: 1px solid #d6dbe3; padding-bottom: 8px; }
        h3 { font-size: 15px; }
        p { margin: 0 0 12px; }
        ul { margin: 0; padding-left: 18px; }
        .card { border: 1px solid #d6dbe3; border-radius: 12px; padding: 16px; margin-bottom: 12px; page-break-inside: avoid; }
        .badge { display: inline-block; padding: 4px 8px; border-radius: 999px; font-size: 12px; background: #ecf2f9; color: #285784; margin-left: 8px; }
        .muted { color: #576579; font-size: 13px; }
        .grid { display: grid; grid-template-columns: repeat(2, 1fr); gap: 12px; }
        .risk { border-left: 4px solid #dc2626; }
        .feature { border-left: 4px solid #0f766e; }
        .effort { border-left: 4px solid #7c3aed; }
      </style>
    </head>
    <body>
      <h1>${escapeHtml(data.project_summary)}</h1>
      <p class="muted">Generated by Proplytics</p>

      <h2>Features</h2>
      ${data.features
        .map(
          (feature) => `
            <div class="card feature">
              <h3>${escapeHtml(feature.title)} <span class="badge">${escapeHtml(feature.confidence_pct)}% confidence</span></h3>
              <p>${escapeHtml(feature.description)}</p>
              <p><strong>Approach:</strong> ${escapeHtml(feature.technical_approach)}</p>
            </div>
          `
        )
        .join('')}

      <h2>Risks</h2>
      ${data.risks
        .map(
          (risk) => `
            <div class="card risk">
              <h3>${escapeHtml(risk.label)} <span class="badge">${escapeHtml(risk.severity)} severity</span></h3>
              <p><strong>Category:</strong> ${escapeHtml(risk.category)}</p>
              <p>${escapeHtml(risk.mitigation)}</p>
            </div>
          `
        )
        .join('')}

      <h2>Timeline</h2>
      ${data.timeline
        .map(
          (phase) => `
            <div class="card">
              <h3>${escapeHtml(phase.phase)} <span class="badge">${escapeHtml(phase.duration)}</span></h3>
              <ul>${renderList(phase.tasks)}</ul>
            </div>
          `
        )
        .join('')}

      <h2>Effort</h2>
      ${data.effort
        .map(
          (effort) => `
            <div class="card effort">
              <h3>${escapeHtml(effort.label)} <span class="badge">${escapeHtml(effort.percentage)}%</span></h3>
              <p>${escapeHtml(effort.description)}</p>
              <p class="muted">${escapeHtml(effort.timeframe)}</p>
            </div>
          `
        )
        .join('')}

      ${
        data.market?.length
          ? `
          <h2>Market Signals</h2>
          <div class="grid">
            ${data.market
              .map(
                (item) => `
                  <div class="card">
                    <h3>${escapeHtml(item.title)}</h3>
                    <p>${escapeHtml(item.description)}</p>
                  </div>
                `
              )
              .join('')}
          </div>
        `
          : ''
      }

      ${
        data.impact?.length
          ? `
          <h2>Business Impact</h2>
          <div class="grid">
            ${data.impact
              .map(
                (item) => `
                  <div class="card">
                    <h3>${escapeHtml(item.title)} <span class="badge">${escapeHtml(item.impact_score)}</span></h3>
                    <p>${escapeHtml(item.description)}</p>
                  </div>
                `
              )
              .join('')}
          </div>
        `
          : ''
      }
    </body>
  </html>`;
}

async function generatePDF(proposalData) {
  let browser;

  try {
    browser = await puppeteer.launch({
      headless: true,
      executablePath: env.PUPPETEER_EXECUTABLE_PATH || undefined,
      args: ['--no-sandbox', '--disable-setuid-sandbox'],
    });

    const page = await browser.newPage();
    await page.setContent(buildHTMLTemplate(proposalData), { waitUntil: 'networkidle0' });

    const pdfBuffer = await page.pdf({
      format: 'A4',
      printBackground: true,
      margin: { top: '20mm', right: '16mm', bottom: '20mm', left: '16mm' },
    });

    return pdfBuffer;
  } finally {
    if (browser) {
      await browser.close().catch((error) => {
        if (env.NODE_ENV !== 'production') {
          console.warn('PDF browser cleanup failed:', error.message);
        }
      });
    }
  }
}

module.exports = { generatePDF, buildHTMLTemplate };
