const puppeteer = require('puppeteer');
const { env } = require('../../config/env');

function escapeHtml(value) {
  return String(value || '')
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;')
    .replace(/'/g, '&#039;');
}

function renderList(items) {
  return items.map((item) => `<li>${escapeHtml(item)}</li>`).join('');
}

function renderClassicTimeline(data) {
  return `
    <h2>Timeline</h2>
    ${data.timeline
      .map(
        (phase) => `
          <div class="card">
            <h3>${escapeHtml(phase.phase)} <span class="badge">${escapeHtml(phase.duration)}</span></h3>
            <ul>${renderList(phase.tasks)}</ul>
          </div>
        `
      )
      .join('')}
  `;
}

function renderDeliveryPlan(data, options = {}) {
  const deliveryPlan = data.delivery_plan || {};
  const includeRoadmap = options.includeRoadmap !== false;
  const includeBacklog = options.includeBacklog !== false;
  const includeNotifications = options.includeNotifications !== false;

  return `
    <section class="hero">
      <div class="eyebrow">Structured Delivery Report</div>
      <h1>${escapeHtml(data.project_summary)}</h1>
      <p class="muted">Generated by FixFlowAI for execution-ready proposal handoff.</p>
    </section>

    <h2>Executive Summary</h2>
    <div class="card">
      <p>${escapeHtml(data.project_summary)}</p>
    </div>

    <h2>Weekly Plan</h2>
    ${(deliveryPlan.weeks || [])
      .map(
        (week) => `
          <div class="card week-card">
            <div class="week-header">
              <h3>${escapeHtml(week.label)}</h3>
              <span class="badge">${escapeHtml(week.sourcePhase)}</span>
            </div>
            <div class="two-col">
              <div>
                <div class="section-label">Goals</div>
                <ul>${renderList(week.goals || [])}</ul>
              </div>
              <div>
                <div class="section-label">Tasks</div>
                <ul>${(week.tasks || [])
                  .map((task) => `<li>${escapeHtml(task.title)} <span class="muted">(${escapeHtml(task.status)})</span></li>`)
                  .join('')}</ul>
              </div>
            </div>
            <div class="two-col">
              <div>
                <div class="section-label">Deliverables</div>
                <ul>${renderList(week.deliverables || [])}</ul>
              </div>
              <div>
                <div class="section-label">Dependencies</div>
                <ul>${renderList(week.dependencies || [])}</ul>
              </div>
            </div>
          </div>
        `
      )
      .join('')}

    ${
      includeRoadmap && deliveryPlan.roadmap?.length
        ? `
          <h2>Roadmap</h2>
          <div class="grid">
            ${deliveryPlan.roadmap
              .map(
                (milestone) => `
                  <div class="card roadmap">
                    <h3>${escapeHtml(milestone.title)}</h3>
                    <p><strong>Target:</strong> Week ${escapeHtml(milestone.targetWeek)}</p>
                    <p class="muted">Status: ${escapeHtml(milestone.status)}</p>
                  </div>
                `
              )
              .join('')}
          </div>
        `
        : ''
    }

    ${
      includeBacklog && deliveryPlan.backlog?.length
        ? `
          <h2>Backlog</h2>
          ${deliveryPlan.backlog
            .map(
              (item) => `
                <div class="card backlog">
                  <h3>${escapeHtml(item.title)}</h3>
                  <p><strong>Reason:</strong> ${escapeHtml(item.reason)}</p>
                </div>
              `
            )
            .join('')}
        `
        : ''
    }

    ${
      includeNotifications
        ? `
          <h2>Collaboration Notifications</h2>
          <div class="card">
            <p><strong>Enabled:</strong> ${deliveryPlan.notificationDefaults?.enabled ? 'Yes' : 'No'}</p>
            <p><strong>Channels:</strong> ${escapeHtml((deliveryPlan.notificationDefaults?.channels || []).join(', ') || 'None')}</p>
            <p><strong>Events:</strong> ${escapeHtml((deliveryPlan.notificationDefaults?.events || []).join(', ') || 'None')}</p>
          </div>
        `
        : ''
    }
  `;
}

function buildHTMLTemplate(data, options = {}) {
  const layout = options.layout || 'delivery';

  return `<!DOCTYPE html>
  <html lang="en">
    <head>
      <meta charset="utf-8" />
      <title>FixFlowAI Proposal Export</title>
      <style>
        body { font-family: Arial, sans-serif; color: #162032; margin: 0; padding: 32px; line-height: 1.6; background: #f7fafc; }
        h1, h2, h3 { margin: 0 0 12px; color: #19395c; }
        h1 { font-size: 28px; max-width: 90%; }
        h2 { font-size: 18px; margin-top: 28px; border-bottom: 1px solid #d6dbe3; padding-bottom: 8px; }
        h3 { font-size: 15px; }
        p { margin: 0 0 12px; }
        ul { margin: 0; padding-left: 18px; }
        .card { border: 1px solid #d6dbe3; border-radius: 16px; padding: 16px; margin-bottom: 12px; background: #ffffff; page-break-inside: avoid; box-shadow: 0 8px 24px rgba(15, 23, 42, 0.06); }
        .badge { display: inline-block; padding: 4px 8px; border-radius: 999px; font-size: 12px; background: #ecf2f9; color: #285784; margin-left: 8px; }
        .muted { color: #576579; font-size: 13px; }
        .grid { display: grid; grid-template-columns: repeat(2, 1fr); gap: 12px; }
        .risk { border-left: 4px solid #dc2626; }
        .feature { border-left: 4px solid #0f766e; }
        .effort { border-left: 4px solid #7c3aed; }
        .hero { padding: 28px; border-radius: 24px; background: linear-gradient(135deg, #0f172a, #1d4ed8); color: #f8fafc; margin-bottom: 24px; }
        .hero h1 { color: #f8fafc; }
        .hero .muted { color: rgba(248, 250, 252, 0.82); }
        .eyebrow { text-transform: uppercase; letter-spacing: 0.24em; font-size: 11px; margin-bottom: 12px; color: rgba(191, 219, 254, 0.9); }
        .two-col { display: grid; grid-template-columns: repeat(2, 1fr); gap: 12px; margin-top: 12px; }
        .section-label { font-weight: 700; margin-bottom: 8px; color: #0f172a; }
        .week-header { display: flex; justify-content: space-between; gap: 12px; align-items: center; }
        .roadmap { border-left: 4px solid #2563eb; }
        .backlog { border-left: 4px solid #f97316; }
      </style>
    </head>
    <body>
      ${
        layout === 'delivery'
          ? renderDeliveryPlan(data, options)
          : `
            <h1>${escapeHtml(data.project_summary)}</h1>
            <p class="muted">Generated by FixFlowAI</p>
          `
      }

      <h2>Features</h2>
      ${data.features
        .map(
          (feature) => `
            <div class="card feature">
              <h3>${escapeHtml(feature.title)} <span class="badge">${escapeHtml(feature.confidence_pct)}% confidence</span></h3>
              <p>${escapeHtml(feature.description)}</p>
              <p><strong>Approach:</strong> ${escapeHtml(feature.technical_approach)}</p>
            </div>
          `
        )
        .join('')}

      <h2>Risks</h2>
      ${data.risks
        .map(
          (risk) => `
            <div class="card risk">
              <h3>${escapeHtml(risk.label)} <span class="badge">${escapeHtml(risk.severity)} severity</span></h3>
              <p><strong>Category:</strong> ${escapeHtml(risk.category)}</p>
              <p>${escapeHtml(risk.mitigation)}</p>
            </div>
          `
        )
        .join('')}

      ${layout === 'delivery' ? '' : renderClassicTimeline(data)}

      <h2>Effort</h2>
      ${data.effort
        .map(
          (effort) => `
            <div class="card effort">
              <h3>${escapeHtml(effort.label)} <span class="badge">${escapeHtml(effort.percentage)}%</span></h3>
              <p>${escapeHtml(effort.description)}</p>
              <p class="muted">${escapeHtml(effort.timeframe)}</p>
            </div>
          `
        )
        .join('')}

      ${
        data.market?.length
          ? `
          <h2>Market Signals</h2>
          <div class="grid">
            ${data.market
              .map(
                (item) => `
                  <div class="card">
                    <h3>${escapeHtml(item.title)}</h3>
                    <p>${escapeHtml(item.description)}</p>
                  </div>
                `
              )
              .join('')}
          </div>
        `
          : ''
      }

      ${
        data.impact?.length
          ? `
          <h2>Business Impact</h2>
          <div class="grid">
            ${data.impact
              .map(
                (item) => `
                  <div class="card">
                    <h3>${escapeHtml(item.title)} <span class="badge">${escapeHtml(item.impact_score)}</span></h3>
                    <p>${escapeHtml(item.description)}</p>
                  </div>
                `
              )
              .join('')}
          </div>
        `
          : ''
      }
    </body>
  </html>`;
}

async function generatePDF(proposalData, options = {}) {
  let browser;

  try {
    browser = await puppeteer.launch({
      headless: true,
      executablePath: env.PUPPETEER_EXECUTABLE_PATH || undefined,
      args: ['--no-sandbox', '--disable-setuid-sandbox'],
    });

    const page = await browser.newPage();
    await page.setContent(buildHTMLTemplate(proposalData, options), { waitUntil: 'networkidle0' });

    const pdfBuffer = await page.pdf({
      format: 'A4',
      printBackground: true,
      margin: { top: '20mm', right: '16mm', bottom: '20mm', left: '16mm' },
    });

    return pdfBuffer;
  } finally {
    if (browser) {
      await browser.close().catch((error) => {
        if (env.NODE_ENV !== 'production') {
          console.warn('PDF browser cleanup failed:', error.message);
        }
      });
    }
  }
}

module.exports = { generatePDF, buildHTMLTemplate };
